# Main project info
site_name: datadelivery
site_url: https://datadelivery.readthedocs.io/en/latest/
site_author: Thiago Panini
site_description : >-
  An open source Terraform module that is capable to provide a
  complete AWS infrastructure toolkit to be deployed in any AWS account.

# Source repo
repo_name: ThiagoPanini/datadelivery
repo_url: https://github.com/ThiagoPanini/datadelivery

# Copyright
copyright: |
  Copyright &copy; 2023-2024 <a href="https://github.com/ThiagoPanini"  target="_blank" rel="noopener">Thiago Panini</a>

# Extra config
extra:
  # Social media on footer
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ThiagoPanini
      name: Thiago Panini no Github
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/thiago-panini/
      name: Thiago Panini no LinkedIn
    - icon: fontawesome/brands/hashnode
      link: https://panini.hashnode.dev/
      name: Blog panini-tech-lab no Hashnode
  
  # Google Analytics
  analytics:
    provider: google
    property: G-117P7B79M6
    feedback:
      title: This page was helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: Yes, awesome!
          data: 1
          note: >-
            Thank you for your feedback!
        - icon: material/thumb-down-outline
          name: No, it needs improvements!
          data: 0
          note: >- 
            Thank you for your feedback!

# Theme setup
theme:
  name: material

  # Custom dir for theme customization
  custom_dir: docs/overrides

  # Customizing the icon on the page header
  icon:
    logo: custom/custom-icon-32px
  
  # Customizing favicon (brose header)
  favicon: assets/imgs/logo/logo-sem-nome.png

  # Color palettes
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Toque para modo escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/weather-night
        name: Toque para modo claro

  # Documentation features
  features:
    - navigation.tabs
    - navigation.top
    - navigation.instant
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
    - content.tooltips
    - search.share
    - search.highlight
    - search.suggest
    - content.code.copy

# Navigation
nav:
  - Home:
    - datadelivery: index.md
    
  - Quickstart:
    - Overview: quickstart/overview.md
    - Getting Started:
      - Calling the Module: quickstart/calling-the-module.md
      - Module Variables: quickstart/variables.md
      - Customizing the Module: quickstart/customizing-call.md

  - Deep Dive:
    - More About the Module: about/index.md
    - Project Story: about/story.md
    - Design: about/design.md

  - Contributing: contribuindo/contribuindo.md

# Extensions
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - footnotes
  - markdown.extensions.tables
  - markdown.extensions.footnotes
  - attr_list
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - attr_list
  - md_in_html

# Plugins
plugins:
  - search:
      lang: pt
  - mkdocstrings
  - drawio_file
  - glightbox
  - git-committers:
      repository: ThiagoPanini/datadelivery
      branch: main
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# Custom CSS
extra_css:
  - assets/stylesheets/extra.css